[agent]
  interval = "10s"
  flush_interval = "10s"

###############################################################################
# INPUT: Influx Line Protocol listener
###############################################################################
[[inputs.socket_listener]]
service_address = "udp://:8125"
  data_format = "influx"

###############################################################################
# OUTPUT: Prometheus client endpoint
###############################################################################
[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"